dist: xenial

language: python

python:
  - '3.6'
  - '3.7'

before_install:
  - pip install pytest coverage

install:
  - pip install .

cache: pip

# run tests
script:
  - coverage run -m pytest -k 'not shell'

after_success:
  - bash <(curl -s https://codecov.io/bash)
