dist: xenial

language: python

python:
    - '3.6'
    - '3.7'

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

cache: pip

# run tests
script:
  - pytest

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
