dist: xenial

language: python

python:
  - '3.7'
  - '3.8'
  - '3.9'

git:
  depth: false

before_install:
  - pip install pytest coverage

install:
  - pip install .

cache: pip

addons:
  sonarcloud:
    organization: "sharm294"

# run tests
script:
  - coverage run -m pytest -k 'not shell'
  - coverage xml -i
  - sonar-scanner

after_success:
  - bash <(curl -s https://codecov.io/bash)
